src/main/scala/com/lightbend/coursegentools/Linearize.scala, src/main/scala/com/lightbend/coursegentools/LinearizeCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/package.scala
Fixes a bug which cause a problem if a master repo was linearized
into an already existing folder containing a linearized version
of that repo.
In this new version, this situation is detected and the linearization
is aborted.
A new command line option is provided to automatically delete an
already existing destination folder
=> Handle pre-existing linearize destination folder

sbtStudentCommands/Man.scala.template
Added a flag in the printOut method because a bullet "- " was messing with the colouring.
=> Add flag for code fence while printing instructions

README.md
should be 'showExerciseId'. tested with sbt on FTTS-fast-track-scala-exercises-2.0.0 repo.
=> Update README.md for showExerciseID typo

src/main/scala/com/lightbend/coursegentools/Linearize.scala
We now check that the course master project's git workspace and index
are clean. If not, an error message is printed stating that all
changes should be committed first and the command exits.
=> Check that git workspace is clean before linearizing a project

createRelease.sh
Current version of createRelease.sh assumes that slides are in
project root folder.
This change will instead copy 'deck' folder if such a folder exists
in the project, otherwise it will do what it used to do before.
=> Add support for slide deck in a subfolder named 'deck'

sbtStudentCommands/Man.scala.template
The global man command functionality was accidentally disabled. This restores it.
=> Restore global man command functionality

README.md, build.sbt, src/main/resources/reference.conf, src/main/scala/com/lightbend/coursegentools/Helpers.scala, src/main/scala/com/lightbend/coursegentools/MasterAdm.scala, src/main/scala/com/lightbend/coursegentools/MasterAdmCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/MasterSettings.scala, src/main/scala/com/lightbend/coursegentools/Studentify.scala, src/main/scala/com/lightbend/coursegentools/package.scala
Add "masteradm" command with the following options:
- Re-generate the master project build file
- Configure name of master base project
- Delete an exercise
- Duplicate a given exercise and insert before that exercise
- Renumber all exercises
- default is to start from 0 and increment by one
- optionally specify an offset to start numbering
- optionally specify "space" between consecutive
exercises
- Move list of files to clean-up after "studentification" to config
- Update documentation
=> Add master adm command and doc update

src/main/scala/com/lightbend/coursegentools/Linearize.scala
The `linearize` command was doing its task in a very inefficiently as it 'dragging' along all the artifacts created in the `target` folders. The mechanism (using `git`) already in-place to avoid this wasn't inadvertently by-passed. This has now been fixed resulting in a huge speed-up.
=> Eliminate inefficiency in Linearize implementation

src/main/scala/com/lightbend/coursegentools/DeLinearize.scala, src/main/scala/com/lightbend/coursegentools/DeLinearizeCmdLineOptParse.scala
- Argument names & order were swapped, both in `scopt` def and in
call to `delinearize` method. This caused the command to work
when passing the masterRepo as the first argument and the
folder holding the linearized repo as the second argument.
Obviously, this was the opposite order of the one shown by
`scopt` in the "Usage:" message which was very confusing.
In summary, the masterRepo is always the first argument in
both the `linearize` and the `delinearize` command
=> Fix swapping of command arguments in two places

sbtMasterCommands/MPSelection.scala.template, sbtMasterCommands/Navigation.scala.template, sbtStudentCommands/Navigation.scala.template, src/main/resources/reference.conf, src/main/scala/com/lightbend/coursegentools/Helpers.scala, src/main/scala/com/lightbend/coursegentools/MasterSettings.scala, src/main/scala/com/lightbend/coursegentools/Studentify.scala, src/main/scala/com/lightbend/coursegentools/package.scala
Until now, the different exercises in the master project had to have a name prefixed by the fixed string _exercise_.
This is now configurable via the `studentify.exercise-project-prefix` setting.
Add this setting to set the prefix to the one you use in the master project
=> Make project prefix in master configurable

sbtMasterCommands/StudentCommandsPlugin.scala.template, sbtStudentCommands/Navigation.scala.template, sbtStudentCommands/StudentCommandsPlugin.scala.template
- The exercise description in the sbt prompt is now generated from
the project name corresponding to the exercise. The prefix and
exercise number is deleted and the remainder is copied in the
prompt whereby underscores are replaced with spaces. Also,
capitalisation is preserved.
- Breaking change: the convention to extract the exercise description
is no longer followed. Hence this line, if present in projects
can be removed.
- The 'listExercises' command's output has been changed to show
the full exercise project name. This is more useful than the
reformatted string that couldn't really be linked to the
project name.
=> Make prompt in master repo and studentified version consistent

sbtMasterCommands/Man.scala.template, sbtStudentCommands/Man.scala.template, sbtStudentCommands/Navigation.scala.template, src/main/resources/reference.conf, src/main/scala/com/lightbend/coursegentools/Helpers.scala, src/main/scala/com/lightbend/coursegentools/MasterSettings.scala
Apart from the default location of the README.md files in
`project/src/test/resources/README.md`, an alternate location can be
selected by setting `studentify.readme-files-in-exercise-root-folder`
to `true` in configuration
=> Add support for alternate location of README file in exercises

sbtStudentCommands/Pssr.scala.template, src/main/scala/com/lightbend/coursegentools/GenTests.scala, src/main/scala/com/lightbend/coursegentools/MasterAdm.scala, src/main/scala/com/lightbend/coursegentools/MasterAdmCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/package.scala
- This new option will generate a test script for a given master
repository that exercises various commands linked to the
Course Management Tools:
- On the master repo:
- `man e` on each project step.
- `sbt compile/test` on each project step.
- On a studentified version of the repo:
- `man e' on each project step.
- `listExercises`.
- `nextExercise`, `prevExercise`, `pullSolution`.
- `sbt compile/test` on each project step.
- `gotoExercise` and `gotoExerciseNr`
- `gotoFirstExercise`
- `saveState`, `restoreState` and `savedStates`
- Unrelated: changes 'savedStates' to give a sorted list of saved states
- This new feature will be used to test the proper functioning of
master repositories (note, of course, that the proper functioning
of the contained exercise code is a responsibility of the …
=> Add test script generation option to masteradm

cpCleanViaGit.sh
Using a static name for the temporary remote on the master git repo is
not very robust. In case the cleanup is not performed (for example
in case the execution of 'studentify' or 'linearize' is interrupted
by the user), subsequent runs of 'studentify' or 'linearize' will
fail systematically. With this change, the added remote gets a random
name (UUID) prefixed by the string 'CMT-'.
=> Make cpCleanViaGit more robust

src/main/scala/com/lightbend/coursegentools/Helpers.scala
Until now, exercise project names and some "CMT" settings couldn't contain
special characters, a dash ('-') being one of them. This creates problems
for users that are hard to troubleshoot for anyone 'sbt-unaware'.
Any setting that may be used in creating `val` names, will now be surrounded
by back-ticks, effectively eliminating this issue.
Verified proper functioning on a couple of repos (one of which is [alpakka-sample-http-csv-to-kafka](https://github.com/akka/alpakka-samples/tree/master/alpakka-sample-http-csv-to-kafka))
=> Surround project names with back-ticks

sbtLinearizeCommands/Man.scala.template, sbtLinearizeCommands/Navigation.scala.template, sbtLinearizeCommands/StudentCommandsPlugin.scala.template, sbtLinearizeCommands/StudentKeys.scala.template, src/main/scala/com/lightbend/coursegentools/Helpers.scala, src/main/scala/com/lightbend/coursegentools/Linearize.scala, src/main/scala/com/lightbend/coursegentools/LinearizeCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/Studentify.scala, src/main/scala/com/lightbend/coursegentools/package.scala
- Added support for linearization of a Dotty project
- A linearized project used to be not loadable in sbt. This is inconvenient
as it prevents using an IDE (or sbt session) from being used during
interactive rebasing of the linearized repo
=> dotty support for linearize; make Linearized repo loadable in sbt

cpCleanViaGit.sh, src/main/scala/com/lightbend/coursegentools/GenTests.scala
- Github Actions require setting bash fast fail options (-e and
-o fastfail) to be set one-by-one
- Fixing of the script that makes a clean copy of a master repo
to also work insode of a Github Action plugin
- Add some clarifications to the copy script
=> Fix scripting in preparation of CI/CD enablement

sbtLinearizeCommands/StudentCommandsPlugin.scala.template, src/main/resources/reference.conf, src/main/scala/com/lightbend/coursegentools/Helpers.scala, src/main/scala/com/lightbend/coursegentools/MainSettings.scala
- Default behavior is to asume a `common` project is present
- Disable `common` project by setting `studentify.common-project-enabled`
to `false`
=> Make 'common' project optional via CMT configuration

src/main/scala/com/lightbend/coursegentools/Helpers.scala
Resolves #98
- `mainadm -c` didn't take into account setting
`studentify.readme-in-test-resources`
=> Fix mainadm issue with soundness check of main repository

course-templates/dotty-cmt-template-common/project/StudentCommandsPlugin.scala, course-templates/dotty-cmt-template-no-common/project/StudentCommandsPlugin.scala, course-templates/play-cmt-template-no-common/project/CommonSettings.scala, course-templates/play-cmt-template-no-common/project/StudentCommandsPlugin.scala, course-templates/scala-cmt-template-common/project/StudentCommandsPlugin.scala, course-templates/scala-cmt-template-no-common/project/StudentCommandsPlugin.scala, sbtLinearizeCommands/Man.scala.template, sbtLinearizeCommands/StudentCommandsPlugin.scala.template, sbtMainCommands/Man.scala.template, sbtMainCommands/StudentCommandsPlugin.scala.template, sbtStudentCommands/StudentCommandsPlugin.scala.template
Fixes #110 
Add `shellPrompt` settings to project level sbt config.
=> Fix sbt shellPrompt rendering failure on Play projects

.github/workflows/ci.yml
- Add release action
- Use `Coursier`to generate binary launchers
- Upload generated binaries as a zip archive to release assets.
> Users downloading the artifacts should add `course-management-tools/bin` to `$PATH`
=> Setup release pipeline using github actions

.github/workflows/ci.yml, .sbtopts, core/src/main/scala/com/lightbend/coursegentools/GenTests.scala
**Add support for generating test script on different environments.**
- A system property is introduced in file `.sbtopts`
- Perform script generation based on the system property.
- `Coursier bootstrap` supports adding `Java Option` to the generated artifact using option `--java-opt`
- CI pipeline is adapted to add this new option to the generated binaries
=> Adapt test script generation to support cmt binaries

core/src/main/scala/com/lightbend/coursegentools/Helpers.scala, linearize/src/main/scala/com/lightbend/coursegentools/Linearize.scala, studentify/src/main/scala/com/lightbend/coursegentools/Studentify.scala
- As of git version 2.28.0, the default branch name can be set
via `git config --global init.defaultBranch main` (setting it to
`main`.
This was not accounted for when running `linearize` or `studentify -g`
- This fix wil do the renaming only if the default branch name is not
`main`
=> Fix studentify & linearize default branch naming to 'main'

.github/workflows/publish-docs.yml
Any new changes inside `docs` and `website` folders merged to `main` branch gets published to `github pages`.
To make this PR complete, the following changes need to be made on repository settings.
Generate a fresh SSH key using `ssh-keygen`
```sh
mkdir github
cd github
ssh-keygen -t rsa -b 4096 -C "youremail@gmail.com"
Enter file in which to save the key (/Users/robinraju/.ssh/id_rsa): cmt
Enter passphrase (empty for no passphrase): <ENTER, NO PASSPHRASE>
Enter same passphrase again: <ENTER, NO PASSPHRASE>
Your identification has been saved in cmt.
Your public key has been saved in cmt.pub.
```
Copy the public key to clipboard
```sh
cat cmt.pub | pbcopy
```
Open the "Deploy key" menu in project settings: https://github.com/eloots/course-management-tools/settings/keys/new
Paste the key …
=> Setup CI to publish documentation to github pages

website/core/Footer.js
- Probably caused multi-language support in docusaurus that we
don't fully understand.
- Assuming for the time being thatwe only will support docs in
English.
=> Fix broken links in footer in reference pages

core/src/main/scala/com/lightbend/coursegentools/Helpers.scala
- An error message was referring specifically to `cmt-studentify`
whereas it can thrown by other CMT commands
=> Change wording in error message

core/src/main/scala/com/lightbend/coursegentools/Helpers.scala, core/src/main/scala/com/lightbend/coursegentools/ProcessDSL.scala, delinearize/src/main/scala/com/lightbend/coursegentools/DeLinearize.scala, linearize/src/main/scala/com/lightbend/coursegentools/Linearize.scala, mainadm/src/main/scala/com/lightbend/coursegentools/MainAdm.scala, studentify/src/main/scala/com/lightbend/coursegentools/Studentify.scala
This PR tries to fix an error resolving the main repo path relative to the current directory. 
Before:
`Executing CMT commands from a course  repo`
```sh
cmt-mainadm -t test.sh .
ERROR: No exercises found in .
```
```sh
cmt-linearize -dot . ../lin
CHECKING WORKSPACE in .
Destination folder ../lin/. exists: Either remove this folder
manually or use the '-f' command-line option to delete it automatically
```
```sh
cmt-studentify -dot . ../stu
CHECKING WORKSPACE in .
Initialized empty Git repository in /private/var/folders/50/tgcdyndd6h37trb0dpk5yjrc0000gn/T/sbt_889bd37f/..git/
To /var/folders/50/tgcdyndd6h37trb0dpk5yjrc0000gn/T/sbt_889bd37f/..git
* [new branch]      HEAD -> A7ECFDFA-A8E0-471F-9970-F68F6636AE35
fatal: destination path '.' already exists and is not an empty directory.
ERROR: …
```
=> Resolve main repo path based on context

cmta/src/main/scala/cmt/admin/command/execution/Studentify.scala, core/src/main/resources/reference.conf, core/src/main/scala/cmt/CMTaConfig.scala, core/src/main/scala/cmt/CMTcConfig.scala, core/src/main/scala/cmt/Helpers.scala
A studentified repo contains a number of (hidden) metadata folders
and files that were located either in the root folder of the
repo or in the `.cue` folder
To reduce the clutter (and to avoid distraction for the user of the
repo), all these folders and files have now been moved to a single
`.cmt` folder in the root of the repo.
This is the list of moved files and folders:
- `.bookmark`     => `.cmt/.bookmark`
- `.cmt-config`   => `.cmt/.cmt-config`
- `.cue`          => `.cmt/.cue`
- `.savedStates`  => `.cmt/.savedStates`
=> Move all CMT related files & folders to a dedicated folder

core/src/main/scala/cmt/Helpers.scala
- When passing a `File` to `fileList`, the latter now return
a collection holding the `File` if it corresponds to an existing
file. Before this change, an empty Vector would be returned.
=> Adapt 'fileList' to cover a corner case

cmtc/src/main/scala/cmt/client/command/execution/GotoExercise.scala, cmtc/src/main/scala/cmt/client/command/execution/ListExercises.scala, cmtc/src/main/scala/cmt/client/command/execution/NextExercise.scala, cmtc/src/main/scala/cmt/client/command/execution/PreviousExercise.scala, cmtc/src/main/scala/cmt/client/command/execution/PullSolution.scala, cmtc/src/main/scala/cmt/client/command/execution/PullTemplate.scala, cmtc/src/main/scala/cmt/client/command/execution/SaveState.scala, cmtc/src/main/scala/cmt/client/command/execution/package.scala
- Fixes #184
- `cmtc goto-exercise`: Add missing check if current exercise is the one specified to go to
- factor out code to get current exercise ID
- Minor refactoring of code for better readbility
=> Fix goto exercise and goto first exercise

core/src/main/scala/cmt/core/cli/CliParser.scala, core/src/main/scala/cmt/core/cli/ScoptCliParser.scala
- In Scala 3, the wildcard for a type parameter is `?` (instead of `_` in Scala 2)
=> Fix Scala 3 deprecation warning - wildcard type parameter issue

cmtc/src/main/scala/cmt/client/Configuration.scala, cmtc/src/test/scala/cmt/client/ConfigurationSpec.scala
Adds the domain objects for handling global configuration. That is, the `CMT_HOME` directory and the core `cmt` configuration that will point to the current course the student is working on in this installation and where the courses are stored in their local install.
=> global configuration

cmtc/src/main/scala/cmt/client/Configuration.scala, cmtc/src/main/scala/cmt/client/Main.scala, cmtc/src/main/scala/cmt/client/cli/CmtcCommand.scala, cmtc/src/main/scala/cmt/client/command/Executable.scala, cmtc/src/main/scala/cmt/client/command/SetCurrentCourse.scala, cmtc/src/test/scala/cmt/client/command/SetCurrentCourseSpec.scala, core/src/main/scala/cmt/Error.scala
Adds support for setting a current course.
This is the initial version of this functionality and currently it just takes the directory given in the options to the command and sets the `current-course` property of the global configuration to the absolute path of this file.
=> Added set-current-course command

cmtc/src/main/scala/cmt/client/command/ListSavedStates.scala, cmtc/src/main/scala/cmt/client/command/PullSolution.scala, cmtc/src/main/scala/cmt/client/command/PullTemplate.scala, cmtc/src/main/scala/cmt/client/command/RestoreState.scala, cmtc/src/main/scala/cmt/client/command/SaveState.scala
- Print out a more meaningful message when `cmtc list-saved-states` is run and no previously saved states are available
- Make colouring of success messages consistent between commands
=> Change command success messages

cmta/src/main/scala/cmt/admin/command/Delinearize.scala, cmta/src/main/scala/cmt/admin/command/Linearize.scala, cmta/src/main/scala/cmt/admin/command/Studentify.scala, cmta/src/test/scala/cmt/admin/cli/DelinearizeArgumentsSpec.scala, cmta/src/test/scala/cmt/admin/cli/LinearizeArgumentsSpec.scala, cmta/src/test/scala/cmt/admin/cli/StudentifyArgumentsSpec.scala
- Commands `studentify`, `linearize`, and `delinearize` now use the same `-d` short option name to specifiy the studentified/linearized base folder
=> Harmonize short option for destination folder cmta

cmtc/src/main/scala/cmt/client/command/GotoFirstExercise.scala, cmtc/src/main/scala/cmt/client/command/NextExercise.scala, cmtc/src/main/scala/cmt/client/command/PreviousExercise.scala
- Three commands were missing the `-d` force move short option name
=> Add missing short option name to move between exercises commands

.github/workflows/ci.yml, build.sbt, cmtc/src/main/scala/cmt/client/Configuration.scala, cmtc/src/main/scala/cmt/client/Helpers.scala, cmtc/src/main/scala/cmt/client/command/ListExercises.scala, cmtc/src/main/scala/cmt/client/command/SetCurrentCourse.scala, cmtc/src/test/scala/cmt/client/ConfigurationSpec.scala, cmtc/src/test/scala/cmt/client/command/SetCurrentCourseSpec.scala, project/Build.scala, project/Dependencies.scala, project/build.properties
- Use dev-dirs library to determine location for saving:
- CMT specific config file
- CMT specific data such as installed courses
- Validate CMT root folder passed to `set-current-course` command
- Print information about the current course when successfully running the `set-cuurent-course` command
`cmtc set-current-course` will list the exercises in the studentified CMT repository that is passed to it as an argument:
```
$ cmtc set-current-course -s ~/tmp/stu/lunatech-scala-2-to-scala3-course/code/src/main
Current course set to '/Users/ericloots/tmp/stu/lunatech-scala-2-to-scala3-course'
Exercises in repository:
1.      exercise_000_sudoku_solver_initial_state
2.      exercise_001_dotty_deprecated_syntax_rewriting
3.      exercise_002_dotty_new_syntax_and_indentation_based_syntax
4. …
```
=> Introduce dirs-dev 

core/src/main/scala/com/lunatech/cmt/Helpers.scala
When CMT configuration setting `studentified-repo-active-exercise-folder` is set to `"."`, the exercise code is put in the root folder of the studentified artefact when studentifying a course.
This commit fixes the problem that overwrote the CMT configuration folder in the studentified artifact. The fix consists of tuning the `cmt-studentified-dont-touch` configuration setting in the studentified artifact.
For example, with this main CMT configuration file:
```
studentified-repo-active-exercise-folder = code
cmt-studentified-dont-touch = [
.idea
.bsp
.bloop
.vscode
.metals
project/target
project/project
]
```
the resulting studentified artifact configuration settings are:
```
"active-exercise-folder" : "code",
"cmt-studentified-dont-touch" : [
"code/.idea",
"code/.bsp",
"code/.bloop", …
```
=> Fix issue with exercises in root folder studentified repo

build.sbt, project/Build.scala
- Settings should apply to all sbt projects
=> Fix publish info

.github/workflows/ci.yml
Unless I'm misunderstanding something, we don't need this `CMT` abstraction right? Can't we just rely on the checked out dir that is created when it clones and we can avoid having the `cd CMT` in various places?
=> refactor(ci): just use the default cloned course-management-tools dir

.github/workflows/release.yml, .github/workflows/validate.yml, build.sbt, cmta/src/main/resources/reflect-config.json, cmta/src/main/resources/resource-config.json, cmtc/src/main/resources/reflect-config.json, cmtc/src/main/resources/resource-config.json, cmtc/src/main/scala/com/lunatech/cmt/client/command/Install.scala, project/Build.scala
This add some specific settings to try and generative native images. Mainly it does the following:
1. Add some extra settings to not create a fallback image, which needs a JVM to run. Now, if something is wrong and it can't generate a standalone image, it will fail
2. Restructure CI to not run formatting checks multiple times
3. Introduce mac to the os matrix to test image generation. In theory the dev dirs stuff is also a bit different on mac, so I kept running the tests on all 3 as well.
=> Generate native images

cmtc/src/main/scala/coursemgmt/client/command/Install.scala
Hi,
I looked at the changes you did in https://github.com/scalacenter/course-management-tools/pull/301/commits/b9c29d188b1878ac8d80b2ee016e88b2653e96b6 and noticed that these do not behave in the same way as before.
To mimic a **move** the directory needs to be **deleted** after the `copyDirectory`-call.
Linked Issue: https://github.com/scalacenter/course-management-tools/issues/297
=> Add a delete call to preserve move behavior
