scalacenter/course-management-tools

validateStudentRepo.sh
validateStudentRepo.sh didn't run the tests for the first exercise in a course master repository.
Fixes issue #34
=> Fix skipping validation of first exercise

sbtStudentCommands/Man.scala.template, sbtStudentCommands/Navigation.scala.template, sbtStudentCommands/Pssr.scala.template, sbtStudentCommands/StudentCommandsPlugin.scala.template
- Depending on the use case, the color 'Console.BLUE' is
changed to 'Console.YELLOW' or 'Console.GREEN'
- This has been verified to work for both light and
dark backgrounds
=> Change utilization of color BLUE to GREEN or YELLOW

src/main/scala/com/lightbend/coursegentools/Studentify.scala
Small change to remove Jenkins files from the built repos.
=> Added Jenkinsfile to the cleanup list.

sbtStudentCommands/Man.scala.template, sbtStudentCommands/Navigation.scala.template, sbtStudentCommands/StudentCommandsPlugin.scala.template, sbtStudentCommands/StudentKeys.scala.template, sbtStudentCommands/Zip.scala.template
- Add new command 'gotoExercise' with TAB completion
- Remove unused code
- Simplify code
- Update copyright messages
=> Cleanup/Add 'gotoExercise' command

src/main/scala/com/lightbend/coursegentools/Helpers.scala
Linearize didn't work when setting 'studentify.relative-source-folder'
was set in config.
=> Fix bug in Linearize command

src/main/scala/com/lightbend/coursegentools/ProcessDSL.scala, src/main/scala/com/lightbend/coursegentools/Studentify.scala, src/main/scala/com/lightbend/coursegentools/StudentifyCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/package.scala
- Added `-g` option to `studentify` command
- Fixed a typo in descriptive msg of `savedStates` command
=> Add option to initialise a studentified repo as git repo

project/CommonSettings.scala, project/Dependencies.scala, project/build.properties, src/main/scala/com/lightbend/coursegentools/MasterSettings.scala
=> Bump dependencies/Remove unused dependency

src/main/scala/com/lightbend/coursegentools/Helpers.scala, src/main/scala/com/lightbend/coursegentools/Linearize.scala, src/main/scala/com/lightbend/coursegentools/LinearizeCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/MasterAdm.scala, src/main/scala/com/lightbend/coursegentools/MasterAdmCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/Studentify.scala, src/main/scala/com/lightbend/coursegentools/StudentifyCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/package.scala
Auto reload of build on build def change detection
- This option is enabled by default (as I can't immediately think of a use
case where this would break things)
=> Auto reload build on build def change detection

sbtLinearizeCommands/Navigation.scala.template, sbtStudentCommands/Navigation.scala.template
- Use `trim()` instead of `strip()`
=> Fix compatibility issue (java8)

src/main/scala/com/lightbend/coursegentools/Studentify.scala
- Update .gitignore template to account for VCS & Bloop & Metals
metadata files
=> Update gitignore content

src/main/scala/com/lightbend/coursegentools/CmdOptions.scala, src/main/scala/com/lightbend/coursegentools/GenTests.scala, src/main/scala/com/lightbend/coursegentools/MainAdm.scala, src/main/scala/com/lightbend/coursegentools/MainAdmCmdLineOptParse.scala, src/main/scala/com/lightbend/coursegentools/Studentify.scala
Resolves #97
- Allows for testing the studentified repo when the latter is initialised
as a git repository
=> Add git initialisation option to mainadm when generating test script

.github/workflows/ci.yml
The artifact generated with the `studentify` command can be initialised as a git repository.
This change will generate it as such and then test it
=> Test studentified repo as a git repository

core/src/main/scala/com/lightbend/coursegentools/GenTests.scala
Resolves #111 
Add `linearize` command to the generated test script
=> Add linearize to generated test script

build.sbt, project/CommonSettings.scala, project/Dependencies.scala
- Update organization
- Bump scala version
=> Perform cleanup

website/core/Footer.js, website/siteConfig.js, website/static/img/jetbrains.svg
- Add jetbrains logo in footer
- cleanup siteconfig
=> Add jetbrains opensource support in footer

docs/install.md, docs/your-first-project.md, website/sidebars.json
- Adds sections about the new `cmt-mainadm init` command
- Describes interactive and non-interactive mode documentation
- Demonstration of the process and studentification of a
cloned CMT template
=> Add documentation on cmt-mainadm init command

core/src/main/scala/com/lightbend/coursegentools/Helpers.scala
Fixes #124 
Use config entries from `course-management.conf` for validating course repo.
=> Fixes mainadm repo validation failure

docs/reference-mainadm.md
- update "Usage" section
- refer to "Getting started" section for `cmt-mainadm init`
=> Update cmt-mainadm reference doc

.gitignore, core/src/main/scala/com/lightbend/coursegentools/Helpers.scala, course-templates/dotty-cmt-template-common/project/Dependencies.scala, course-templates/dotty-cmt-template-common/project/build.properties, course-templates/dotty-cmt-template-common/project/plugins.sbt, course-templates/dotty-cmt-template-no-common/project/Dependencies.scala, course-templates/dotty-cmt-template-no-common/project/build.properties, course-templates/dotty-cmt-template-no-common/project/plugins.sbt, course-templates/play-cmt-template-no-common/project/Dependencies.scala, course-templates/play-cmt-template-no-common/project/build.properties, course-templates/play-cmt-template-no-common/project/plugins.sbt, course-templates/scala-cmt-template-common/project/Dependencies.scala, course-templates/scala-cmt-template-common/project/build.properties, course-templates/scala-cmt-template-no-common/project/Dependencies.scala, course-templates/scala-cmt-template-no-common/project/build.properties, project/Dependencies.scala, project/build.properties
This PR updates the course templates with dependencies to the latest sbt and scala versions
=> Update Course templates

project/CommonSettings.scala
Update CMT version before new release
=> Bump cmt version to 1.0.2

mainadm/src/main/scala/com/lightbend/coursegentools/MainAdm.scala, project/CommonSettings.scala
- `cmt-mainadm` incorrectly ran a check to verify that the master folder (defaulting
to the current working folder) is a git repository.
=> Fix cmt mainadm init

core/src/main/scala/cmt/Helpers.scala
- Running the tests changed a developer's global gitconfig
=> Fix bug messing up global gitconfig

cmta/src/main/scala/cmt/admin/command/execution/Linearize.scala, cmta/src/main/scala/cmt/admin/command/execution/Studentify.scala, core/src/main/scala/cmt/Helpers.scala
- Clean-up code
- Rearrange for readability
- Use same code as the linearise command to check if an existing studentified artifact already exists
=> Refactor studentify implementation

.github/workflows/ci.yml
- com.github.eloots -> com.github.lunatech-labs
=> Fix organisation

cmta/src/main/scala/com/lunatech/cmt/admin/command/Version.scala, cmta/src/test/scala/com/lunatech/cmt/RenumberExercisesSpec.scala, cmta/src/test/scala/com/lunatech/cmt/admin/cli/CommandLineArgumentsSpec.scala, cmta/src/test/scala/com/lunatech/cmt/admin/cli/LinearizeArgumentsSpec.scala, cmta/src/test/scala/com/lunatech/cmt/admin/cli/StudentifyArgumentsSpec.scala, cmtc/src/main/scala/com/lunatech/cmt/client/Configuration.scala, cmtc/src/main/scala/com/lunatech/cmt/client/Domain.scala, cmtc/src/main/scala/com/lunatech/cmt/client/Helpers.scala, cmtc/src/main/scala/com/lunatech/cmt/client/command/Install.scala, cmtc/src/main/scala/com/lunatech/cmt/client/command/ListExercises.scala, cmtc/src/test/scala/com/lunatech/cmt/client/cli/CommandLineArgumentsSpec.scala, cmtc/src/test/scala/com/lunatech/cmt/client/cli/InstallArgumentsSpec.scala, core/src/main/scala/com/lunatech/cmt/Helpers.scala, core/src/test/scala/com/lunatech/cmt/support/CommandLineParseTestBase.scala, functional-tests/src/test/scala/com/lunatech/cmt/support/TestSupport.scala, project/Build.scala, project/Dependencies.scala, project/build.properties
- Enable linting (as available since Scala 3.3.0)
- Enable warning about discarded values
- Bump Scala & sbt
=> Enable linting and discarded values warnings

cmtc/src/main/scala/com/lunatech/cmt/client/command/Install.scala, core/src/main/scala/com/lunatech/cmt/Releasables.scala
- Extract CMT project name from zip archive
- Handle "__MACOSX" weirdness on MacOS
- Check pre-existing installs
=> Complete the `cmtc install` from zip file command

cmta/src/main/scala/com/lunatech/cmt/admin/TargetFolderValidation.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Linearize.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Studentify.scala, cmtc/src/main/scala/com/lunatech/cmt/client/command/Install.scala
Some cleanup in `cmtc install` + improved error message
=> Improve `cmtc install` error messages/remove unused code

.github/workflows/ci.yml, build.sbt, project/Build.scala, project/Dependencies.scala
I noticed this in the other prs when I was changing the build files and formatting that it was causing unwanted diffs since formatting wasn't enforced in those files. This fixes that.
=> fix: make sure sbt-related files are also checked for formatting

.github/workflows/release.yml, .github/workflows/validate.yml, .scalafmt.conf, cmtc/src/test/scala/com/lunatech/cmt/client/cli/SetCurrentCourseSpec.scala, core/src/main/scala/com/lunatech/cmt/client/Configuration.scala, core/src/test/scala/com/lunatech/cmt/client/ConfigurationSpec.scala, functional-tests/src/test/scala/com/lunatech/cmt/support/TestSupport.scala
- Release CI split-off from validation bit
- Release only on pushing a release tag
- Snapshot releases not enabled
=> Update ci split off release bits

.github/workflows/release.yml
Coursier command had a hard-coded version.
=> Fix release coursier binaries

cmta/src/main/scala/com/lunatech/cmt/admin/command/Delinearize.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Linearize.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Studentify.scala
=> Format and fix messages from `cmta` `studentify`/`[de]linearize`

.github/workflows/release.yml
=> Temporarily disable release to Sonatype/maven central

cmt-core/src/main/scala/com/lunatech/cmt/Helpers.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Delinearize.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Linearize.scala, cmta/src/main/scala/com/lunatech/cmt/admin/command/Studentify.scala
- Add some progress feedback for `cmta studentify`, `cmta linearize`, and `cmta delinearize` commands
=> Add show cmta progress

cmtc/src/main/scala/com/lunatech/cmt/client/command/Install.scala
=> Fix cmtc install issue
